apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: msg-core-deployment-monitor
spec:
  selector:
    matchLabels:
      app: spring-prometheus-demo
  endpoints:
  - port: http-traffic
    path: "/actuator/prometheus"