apiVersion: v1
kind: Service
metadata:
  name: msg-core-deployment
  labels:
    app: spring-prometheus-demo
spec:
  selector:
    app: spring-prometheus-demo
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8084
      targetPort: 8084